-- Allow multiple reviews per (listing_id, date) via surrogate primary key.

alter table public.reviews drop constraint if exists reviews_pkey;

alter table public.reviews
  add column if not exists id bigint generated by default as identity;

alter table public.reviews
  alter column id set not null;

alter table public.reviews
  add constraint reviews_pkey primary key (id);

create index if not exists reviews_listing_id_date_idx
  on public.reviews (listing_id, date);
